version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: feature_toggle_db
    restart: always
    environment:
      MYSQL_DATABASE: feature_toggle
      MYSQL_USER: user
      MYSQL_PASSWORD: option123
      MYSQL_ROOT_PASSWORD: option123
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data: {}
